### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by georges-g** [AndrewRadev/simple_bookmarks.vim#12]
Hi,

Thanks for the open source work, your plugin is very useful. There are 2 things that could enrich it IMO.

### 1 - Rename the commands

I renamed the commands:
```
:BookAdd
:BookDel
:BookGo
:BookQf
```

I think it makes it easier to group them with autocompletion. If you don't like `Book*`, it could be something like `Bookmark*`.

I also added shortcuts:
```
nnoremap    ,ba         :BookAdd<SPACE>
nnoremap    ,bg         :BookGo<SPACE>
nnoremap    ,bd         :BookDel<SPACE>
nnoremap    ,bq         :BookQf<CR>
```

This could be in the readme or something.

### 2 - Add an option for regex bookmarks

At the moment, bookmarks work with line numbers. I use it for my wiki and specific sections with a title like `line 45: # Todo`.

The problem is those line numbers are changing. If there could be a way to refer to a bookmark with a regex like `^# Todo$`, that would be great.

Just some ideas if you feel like working on this old plugin again. I can give a hand if needed (I know some viml, not much ruby though).

Best

**Comment by AndrewRadev** [comment]
Thanks for your suggestions and your offer to help, I'm glad to see that somebody is finding the plugin useful :)

I've renamed the commands for easier completion and namespacing, I used `:Bookmark*`, maybe even `:SimpleBookmark` would have been best, but this plugin isn't used enough for anybody to complain about naming collisions, I think :).

I've also added a setting called `g:simple_bookmarks_use_pattern`, which is going to do what you're looking for in terms of regexes, or at least I think it should. Actually, for `Go`, jumping to a pattern is essentially always going to be safe, since I could jump to the line and then check if it matches what has been stored. Only the quckfix is explicitly pattern-enabled by the setting. Try it out and let me know if it works as you'd expect.

**Comment by georges-g** [comment]
Thanks for the fast update. Great changes!

IMO, there are still a few problems though.

### Turning off g:simple_bookmarks_use_pattern does not work

If you use `let g:simple_bookmarks_use_pattern = 0`, it still looks for the text and not just the line / column.

### A new line number is not saved

If you use `let g:simple_bookmarks_use_pattern = 1` and change the line number, it finds it, but it does not save the new line number in the storage file `~/.vim_bookmarks`. It will have to do the lookup every time. It's not the best solution IMO.

### dd in quickfix does not work anymore

If have an error probably related to renaming the commands or functions (I had the same problem):
```
Error detected while processing function <SNR>119_DeleteQuickfixBookmark[33]..simple_bookmarks#
Del:
line   11:
E117: Unknown function: simple_bookmarks#Copen
```

### Dealing when the line does not exist anymore

If `let g:simple_bookmarks_use_pattern = 1` and you completely delete the line, it goes back to the line number, which makes sense, but you might want to save the new line value in the storage file, not to do the lookup everytime you load the bookmark again.

Good luck! ;)

**Comment by AndrewRadev** [comment]
> If you use let g:simple_bookmarks_use_pattern = 0, it still looks for the text and not just the line / column.

I thought it might be helpful, but fair enough, I suppose precision is better. It should no longer look for it unless the flag is set.

> If you use let g:simple_bookmarks_use_pattern = 1 and change the line number, it finds it, but it does not save the new line number in the storage file ~/.vim_bookmarks. It will have to do the lookup every time. It's not the best solution IMO.

Updated `BookmarkGo` to also write the updated line, but it won't work for the quickfix window, since that's just fed to Vim.

> If have an error probably related to renaming the commands or functions (I had the same problem):

Yeah, I'd missed that, fixed.

**Comment by georges-g** [comment]
It works great, thanks a lot.

One very last detail: if the line is not found, I would save the new cursor position and line value, in order not to keep doing the lookup every time. I understand this is debatable and if you want to keep it that way, I'm good with it. You tell me.

**Comment by AndrewRadev** [comment]
I feel like saving the new line contents would be counterproductive if changes get undone or if there's git branch switching or something. It's not a lookup that would cost much in terms of performance, so, as you say, I'll keep the current behaviour for now.
